---
- name: "[Debian] Determine required MySQL Python libraries"
  set_fact:
    mysql_python_package: "python3-mysqldb"
  when:
    - ("python3" in ansible_python_interpreter|default(''))
    - ansible_os_family == 'Debian'

- name: "[Debian] Determine required MySQL Python libraries"
  set_fact:
    mysql_python_package: "python-mysqldb"
  when:
    - ("python3" not in ansible_python_interpreter|default(''))
    - ansible_os_family == 'Debian'

- name: "[RedHat] Determine required MySQL Python libraries"
  set_fact:
    mysql_python_package: "MySQL-python"
  when:
    - ansible_os_family == 'RedHat'

- name: Ensure required Python libraries are installed
  package:
    name: "{{ mysql_python_package }}"
    state: present

- name: Create a MySQL backup user
  mysql_user:
    name: "{{ xtrabackup_mysql_user_name }}"
    host: localhost
    password: "{{ xtrabackup_mysql_user_password }}"
    # priv: '*.*:RELOAD,LOCK TABLES,PROCESS,REPLICATION CLIENT,CREATE TABLESPACE,CREATE,INSERT,SELECT'
    # append_privs: true
    state: present

- name: Gather privileges for MySQL backup user
  shell: >-
    set -o pipefail
    &&
    mysql -B --disable-column-names
    -e "SHOW GRANTS FOR {{ xtrabackup_mysql_user_name }}@localhost;" | sed 's/GRANT //;s/ ON .*//' | tr "," "\n" | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//'
  args:
    executable: /bin/bash
  register: xtrabackup_mysql_user_privileges
  changed_when: false

- name: Create fact
  set_fact:
    priv_output: xtrabackup_mysql_user_privileges.stdout_lines

- name: Grant static privileges to MySQL backup user
  shell: >-
    mysql -e
    "GRANT RELOAD,LOCK TABLES,PROCESS,REPLICATION CLIENT,CREATE TABLESPACE,CREATE,INSERT,SELECT ON *.* TO '{{ xtrabackup_mysql_user_name }}'@'localhost';"
  changed_when:
    - '["RELOAD", "LOCK TABLES", "PROCESS", "REPLICATION CLIENT", "CREATE TABLESPACE", "CREATE", "INSERT", "SELECT"] | intersect(priv_output) | length != 8'

- name: Grant dynamic privileges to MySQL backup user
  shell: >-
    mysql -e
    "GRANT BACKUP_ADMIN, BINLOG_ADMIN, SYSTEM_VARIABLES_ADMIN ON *.* TO '{{ xtrabackup_mysql_user_name }}'@'localhost';"
  changed_when:
    - '["BACKUP_ADMIN", "BINLOG_ADMIN", "SYSTEM_VARIABLES_ADMIN"] | intersect(priv_output) | length != 3'

- name: Create .my.cnf file with backup user credentials
  template:
    src: "my.cnf.j2"
    dest: "{{ xtrabackup_system_user.home }}/.my.cnf"
    owner: "{{ xtrabackup_system_user.name }}"
    group: "{{ xtrabackup_system_user.name }}"
    mode: 0600
  when: xtrabackup_create_system_user
