---
- name: "[Debian] Discover repository"
  block:
    - name: Install Repository
      apt:
        deb: "{{ xtrabackup_repository_package }}"
      notify:
        - "[Debian] Enable repository"
        - "[Debian] update cache"

    - meta: flush_handlers
  when:
    - ansible_os_family == 'Debian'

- name: "[RedHat] Install yum repository"
  yum:
    name: "{{ xtrabackup_percona_yum_repository }}"
  when:
    - ansible_os_family == 'RedHat'
