---
- name: "[Debian] Discover repository"
  block:
    - name: Add Percona APT signing key
      apt_key:
        id: 8507EFA5
        keyserver: keyserver.ubuntu.com
        keyring: /etc/apt/trusted.gpg.d/percona.gpg
        state: present
      retries: 3
      delay: 2
    - name: Add Percona Tools APT repository
      apt_repository:
        repo: deb http://repo.percona.com/tools/apt {{ ansible_distribution_release }} main
        filename: percona-tools
        state: present
      retries: 3
      delay: 2
  when:
    - ansible_os_family == 'Debian'

- name: "[RedHat] Install yum repository"
  yum:
    name: "{{ xtrabackup_percona_yum_repository }}"
  when:
    - ansible_os_family == 'RedHat'
