---
- name: Converge
  hosts: all
  roles:
    - role: xtrabackup
      xtrabackup_create_mysql_user: true
      xtrabackup_mysql_user_password: bkpuser

  post_tasks:
    - name: Make sure we can connect to MySQL via Unix socket.
      command: "mysql -u bkpuser -pbkpuser -e 'show databases;'"
      changed_when: false

    - name: Make sure we can connect to MySQL via TCP.
      command: "mysql -u bkpuser -pbkpuser -h 127.0.0.1 -e 'show databases;'"
      changed_when: false
